// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1660881036);
user_pref("browser.search.region", "KG");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Asia/Bishkek");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1660025703068");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220628000715");
user_pref("extensions.lastAppVersion", "91.11.0");
user_pref("extensions.lastPlatformVersion", "91.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"9fafa350-051b-4366-9ca4-d1beb5a49568\",\"google@search.mozilla.org\":\"5e1a805b-3947-4350-abab-1bf02c179c7c\",\"ddg@search.mozilla.org\":\"f608504a-84ac-475d-ad06-96b22ce0ea5a\",\"priceru@search.mozilla.org\":\"24ab2eb8-9ae6-4058-841d-37aa3fefc0ab\",\"wikipedia@search.mozilla.org\":\"9d7945a2-c7d1-403b-85bb-d60b17ec70d3\",\"ozonru@search.mozilla.org\":\"813ab53e-12c6-4038-abeb-0774bd08f657\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "4361a638-e4ab-44d4-b3a6-b31ddc96443");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "33f60a94-a704-48ef-b5c2-26be26c72ef4");
user_pref("toolkit.telemetry.previousBuildID", "20220628000715");
