# Generated by Django 3.2.7 on 2022-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maings', '0003_categoras_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='past',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categor',
        ),
        migrations.AddField(
            model_name='post',
            name='raiting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Categoras',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
